controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template: 'static/index.html.twig'

        # the response status code (default: 200)
        statusCode: 200

        # special options defined by Symfony to set the page cache
        maxAge: 86400
        sharedAge: 86400

        # whether or not caching should apply for client caches only
        private: true

projets:
    path: /projets
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template: 'static/projets.html.twig'

        # the response status code (default: 200)
        statusCode: 200

        # special options defined by Symfony to set the page cache
        maxAge: 86400
        sharedAge: 86400

        # whether or not caching should apply for client caches only
        private: true

watchart:
    path: /watchart
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        # this value can be an absolute path or an absolute URL
        path: 'https://watchart.jbarmengaud.com'
        permanent: true
